title: SQL Commander
description: Lightweight SQL Server exploration, query execution, scripting, and Data API Builder configuration from your browser.
theme: jekyll-theme-merlot
show_downloads: false
google_analytics:

repository: JerryNixon/sql-commander

plugins:
  - jekyll-seo-tag
