title: SQL Commander
description: Lightweight Microsoft SQL Explorer.
theme: jekyll-theme-merlot
show_downloads: false
google_analytics:

repository: JerryNixon/sql-commander

plugins:
  - jekyll-seo-tag
